# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_list <- function(model) {
    .Call(`_RcppScoreDrivenDFM_filter_list`, model)
}

loglik_rcpp <- function(pars, y, T_loc, T_scale, T_shape, Z_loc, Z_scale, Z_shape, stoch_loc, stoch_vol, stoch_shape, NAs, guess_loc, guess_scale) {
    .Call(`_RcppScoreDrivenDFM_loglik_rcpp`, pars, y, T_loc, T_scale, T_shape, Z_loc, Z_scale, Z_shape, stoch_loc, stoch_vol, stoch_shape, NAs, guess_loc, guess_scale)
}

loglik_deriv <- function(pars, y, T_loc, T_scale, T_shape, Z_loc, Z_scale, Z_shape, stoch_loc, stoch_vol, stoch_shape, NAs, guess_loc, guess_scale) {
    .Call(`_RcppScoreDrivenDFM_loglik_deriv`, pars, y, T_loc, T_scale, T_shape, Z_loc, Z_scale, Z_shape, stoch_loc, stoch_vol, stoch_shape, NAs, guess_loc, guess_scale)
}

loglik_hess <- function(pars, y, T_loc, T_scale, T_shape, Z_loc, Z_scale, Z_shape, stoch_loc, stoch_vol, stoch_shape, NAs, guess_loc, guess_scale) {
    .Call(`_RcppScoreDrivenDFM_loglik_hess`, pars, y, T_loc, T_scale, T_shape, Z_loc, Z_scale, Z_shape, stoch_loc, stoch_vol, stoch_shape, NAs, guess_loc, guess_scale)
}

loglik_list <- function(pars, model, give_grad = FALSE, give_hess = FALSE) {
    .Call(`_RcppScoreDrivenDFM_loglik_list`, pars, model, give_grad, give_hess)
}

hstep_filter <- function(y, a_loc_0, a_scale_0, a_shape_0, Z_loc, Z_scale, Z_shape, T_loc, T_scale, T_shape, K_loc, K_scale, K_shape, parameters, NAs) {
    .Call(`_RcppScoreDrivenDFM_hstep_filter`, y, a_loc_0, a_scale_0, a_shape_0, Z_loc, Z_scale, Z_shape, T_loc, T_scale, T_shape, K_loc, K_scale, K_shape, parameters, NAs)
}

filter_reg_list <- function(model) {
    .Call(`_RcppScoreDrivenDFM_filter_reg_list`, model)
}

loglik_reg_rcpp <- function(pars, y, stoch_loc, stoch_vol, stoch_shape, X_loc, X_scale, X_shape, NAs) {
    .Call(`_RcppScoreDrivenDFM_loglik_reg_rcpp`, pars, y, stoch_loc, stoch_vol, stoch_shape, X_loc, X_scale, X_shape, NAs)
}

loglik_reg_list <- function(pars, model) {
    .Call(`_RcppScoreDrivenDFM_loglik_reg_list`, pars, model)
}

loglik_reg_deriv <- function(pars, y, stoch_loc, stoch_vol, stoch_shape, X_loc, X_scale, X_shape, NAs) {
    .Call(`_RcppScoreDrivenDFM_loglik_reg_deriv`, pars, y, stoch_loc, stoch_vol, stoch_shape, X_loc, X_scale, X_shape, NAs)
}

loglik_reg_hess <- function(pars, y, stoch_loc, stoch_vol, stoch_shape, X_loc, X_scale, X_shape, NAs) {
    .Call(`_RcppScoreDrivenDFM_loglik_reg_hess`, pars, y, stoch_loc, stoch_vol, stoch_shape, X_loc, X_scale, X_shape, NAs)
}

